
#  base de données des traductions  (Vocabulaire multi-langues)

LANGUAGES = {
    "Espagnol": {
        "Facile": [
            ("el gato",         "le chat"),
            ("el perro",        "le chien"),
            ("la casa",         "la maison"),
            ("el libro",        "le livre"),
            ("el agua",         "l'eau"),
            ("la mesa",         "la table"),
            ("el sol",          "le soleil"),
            ("la luna",         "la lune"),
            ("el pan",          "le pain"),
            ("la flor",         "la fleur"),
            ("el coche",        "la voiture"),
            ("la ciudad",       "la ville"),
            ("el amigo",        "l'ami"),
            ("la escuela",      "l'ecole"),
            ("el trabajo",      "le travail"),
        ],
        "Moyen": [
            ("el conocimiento", "la connaissance"),
            ("la libertad",     "la liberte"),
            ("el sombrero",     "le chapeau"),
            ("la mariposa",     "le papillon"),
            ("el corazon",      "le coeur"),
            ("la ventana",      "la fenetre"),
            ("el camino",       "le chemin"),
            ("la estrella",     "l'etoile"),
            ("el puente",       "le pont"),
            ("la montagna",     "la montagne"),
            ("el espejo",       "le miroir"),
            ("la tormenta",     "la tempete"),
            ("el bosque",       "la foret"),
            ("la cancion",      "la chanson"),
            ("el silencio",     "le silence"),
        ],
        "Difficile": [
            ("el efimero",      "l'ephemere"),
            ("la nostalgia",    "la nostalgie"),
            ("el amanecer",     "l'aube"),
            ("la serenidad",    "la serenite"),
            ("el crepusculo",   "le crepuscule"),
            ("la eternidad",    "l'eternite"),
            ("el horizonte",    "l'horizon"),
            ("la melancolia",   "la melancolie"),
            ("el desamparo",    "le desarroi"),
            ("la incertidumbre","l'incertitude"),
        ],
    },
    "Anglais": {
        "Facile": [
            ("cat",      "chat"),
            ("dog",      "chien"),
            ("house",    "maison"),
            ("book",     "livre"),
            ("water",    "eau"),
            ("table",    "table"),
            ("sun",      "soleil"),
            ("moon",     "lune"),
            ("bread",    "pain"),
            ("flower",   "fleur"),
            ("car",      "voiture"),
            ("city",     "ville"),
            ("friend",   "ami"),
            ("school",   "ecole"),
            ("work",     "travail"),
        ],
        "Moyen": [
            ("knowledge",   "connaissance"),
            ("freedom",     "liberte"),
            ("butterfly",   "papillon"),
            ("window",      "fenetre"),
            ("journey",     "voyage"),
            ("shadow",      "ombre"),
            ("thunder",     "tonnerre"),
            ("whisper",     "chuchotement"),
            ("mirror",      "miroir"),
            ("silence",     "silence"),
            ("bridge",      "pont"),
            ("forest",      "foret"),
            ("mountain",    "montagne"),
            ("ocean",       "ocean"),
            ("dream",       "reve"),
        ],
        "Difficile": [
            ("ephemeral",       "ephemere"),
            ("serendipity",     "serendipite"),
            ("melancholy",      "melancolie"),
            ("labyrinth",       "labyrinthe"),
            ("ethereal",        "eteree"),
            ("nostalgia",       "nostalgie"),
            ("solitude",        "solitude"),
            ("luminescence",    "luminescence"),
            ("bewilderment",    "desarroi"),
            ("incandescent",    "incandescent"),
        ],
    },
    "Allemand": {
        "Facile": [
            ("die Katze",    "le chat"),
            ("der Hund",     "le chien"),
            ("das Haus",     "la maison"),
            ("das Buch",     "le livre"),
            ("das Wasser",   "l'eau"),
            ("der Tisch",    "la table"),
            ("die Sonne",    "le soleil"),
            ("der Mond",     "la lune"),
            ("das Brot",     "le pain"),
            ("die Blume",    "la fleur"),
            ("das Auto",     "la voiture"),
            ("die Stadt",    "la ville"),
            ("der Freund",   "l'ami"),
            ("die Schule",   "l'ecole"),
            ("die Arbeit",   "le travail"),
        ],
        "Moyen": [
            ("das Wissen",          "la connaissance"),
            ("die Freiheit",        "la liberte"),
            ("der Schmetterling",   "le papillon"),
            ("das Fenster",         "la fenetre"),
            ("die Reise",           "le voyage"),
            ("der Schatten",        "l'ombre"),
            ("der Donner",          "le tonnerre"),
            ("das Schweigen",       "le silence"),
            ("der Spiegel",         "le miroir"),
            ("der Wald",            "la foret"),
        ],
        "Difficile": [
            ("die Sehnsucht",       "le desir nostalgique"),
            ("die Weltanschauung",  "vision du monde"),
            ("das Fernweh",         "l'envie de partir"),
            ("die Einsamkeit",      "la solitude"),
            ("die Dunkelheit",      "l'obscurite"),
            ("das Schicksal",       "le destin"),
            ("die Unendlichkeit",   "l'infini"),
            ("die Verganglichkeit", "la fugacite"),
        ],
    },
    "Italien": {
        "Facile": [
            ("il gatto",        "le chat"),
            ("il cane",         "le chien"),
            ("la casa",         "la maison"),
            ("il libro",        "le livre"),
            ("l'acqua",         "l'eau"),
            ("il tavolo",       "la table"),
            ("il sole",         "le soleil"),
            ("la luna",         "la lune"),
            ("il pane",         "le pain"),
            ("il fiore",        "la fleur"),
            ("la macchina",     "la voiture"),
            ("la citta",        "la ville"),
            ("l'amico",         "l'ami"),
            ("la scuola",       "l'ecole"),
            ("il lavoro",       "le travail"),
        ],
        "Moyen": [
            ("la conoscenza",   "la connaissance"),
            ("la liberta",      "la liberte"),
            ("la farfalla",     "le papillon"),
            ("la finestra",     "la fenetre"),
            ("il viaggio",      "le voyage"),
            ("l'ombra",         "l'ombre"),
            ("il tuono",        "le tonnerre"),
            ("il silenzio",     "le silence"),
            ("lo specchio",     "le miroir"),
            ("il bosco",        "la foret"),
        ],
        "Difficile": [
            ("l'effimero",      "l'ephemere"),
            ("la malinconia",   "la melancolie"),
            ("l'alba",          "l'aube"),
            ("la serenita",     "la serenite"),
            ("il crepuscolo",   "le crepuscule"),
            ("l'eternita",      "l'eternite"),
            ("la solitudine",   "la solitude"),
            ("il destino",      "le destin"),
        ],
    },
}